set nocompatible
filetype off

set shell=/usr/local/bin/cosh
set shellcmdflag=-e
set noshelltemp

map ;; i#!/usr/bin/perluse warnings;use strict;
map <C-U> :!$ urlview %<CR>
map <C-l> :CtrlPTag<CR>
map <C-d> :CtrlPGrep<CR>
map <leader>gf :e <cfile><cr>
map <leader>p :CtrlP<CR><C-\>w
map <leader>l :CtrlPTag<CR><C-\>w
map <leader>d :CtrlPGrep<CR><C-\>w
map <leader>ge :%s/>[  ]\{4}/>>/<CR>
:command S SyntasticCheck

set history=1000
set wildmode=list:longest
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
nnoremap <C-o> :e#<CR>
set ruler

set shiftwidth=4
set softtabstop=4
set shiftround
set expandtab
set autoindent
set hlsearch
set incsearch
set path+=**
set wildmenu
set wildmode=list:longest,full

set backspace=indent,eol,start
syntax enable

colorscheme default
set tw=70

autocmd BufNewFile,BufRead *.s    set syntax=off
autocmd BufNewFile,BufRead *.txt  set syntax=off
autocmd BufNewFile,BufRead *.t    set syntax=perl
autocmd BufNewFile,BufRead *.spec set tw=0
autocmd BufNewFile,BufRead *.html set tw=0
autocmd BufNewFile,BufRead *.ch   set tw=0
autocmd BufNewFile,BufRead /tmp/mutt-* :silent! %s/^\([>|]\s\?\)\+/\=substitute(submatch(0), '\s', '', 'g').' '
autocmd BufNewFile,BufRead /tmp/mutt-* :silent! %s/¹/'/g
autocmd BufNewFile,BufRead /tmp/mutt-* :silent! %s/²/'/g
autocmd BufNewFile,BufRead /tmp/mutt-* :silent! %s/³/'/g
autocmd BufNewFile,BufRead /tmp/mutt-* :silent! %s/Œ/'/g
autocmd BufNewFile,BufRead /tmp/mutt-* :silent! %s//\r> /g
autocmd BufNewFile,BufRead /tmp/mutt-* :silent! %s/﻿//

let g:ctrlp_custom_ignore = 'blib'

let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [], 'passive_filetypes': [] }
let g:syntastic_enable_perl_checker = 1
let g:syntastic_perl_checkers = ['perl', 'podchecker']
let g:syntastic_always_populate_loc_list = 1
let g:LargeFile = 10

" za - toggle fold at cursor.
"augroup XML
"    autocmd!
"    autocmd FileType xml setlocal foldmethod=indent foldlevelstart=999 foldminlines=0
"augroup END

set tags=./tags,tags;

let g:ctrlp_max_height = 100
let g:ctrlp_max_files=0
"autocmd BufWritePost *.pl,*.pm,*.java,*.c,*.py silent! !$ /home/tomh/bin/wrapper-ctags .
