killall xautolock
xautolock -time 10 -locker "i3lock" &
xsetroot -solid grey
xmodmap /home/tomh/dotfiles/profiles/work/Xmodmap2
xset r rate 250 50 &
xrdb -merge $HOME/.Xresources
xsetroot -cursor_name left_ptr
ulimit -c unlimited
xbanish &
urxvtd &
redshift &
autocutsel-local &
export MAWLED_TERMINAL=urxvt
#/home/tomh/scripts/xrandr-monitor
urxvt &
systemctl --user start xfce4-notifyd.service
exec xmonad
#exec mawled
