#!/bin/sh
setxkbmap -option
xmodmap $HOME/.Xmodmap
xset r rate 200 50
xset b off
xrdb -load $HOME/.Xresources
urxvtd &
redshift -l -27.46:153.02 > /dev/null 2>&1 &
export MAWLED_TERMINAL="urxvt +ptab"
exec xmonad
